"use client"
import Head from "next/head";
import BootstrapCarousel from "/Users/yerbolkuldeyev/lighthouse/cleanTS/clean/app/components/navigation/carousel/Bootstrap";

export default function Home() {
  return (
    <>
      <div className="container mx-auto px-4">
        <h1>Hello word</h1>
        <p>Some text</p>

        <div>
          <Head>
            <title>Next.js Carousels</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <BootstrapCarousel />
          </main>
        </div>

        <div className="w-full h-screen bg-green-300"></div>
        <p>
          Some more text
        </p>
      </div>
    </>
  );
}
